In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

import numpy as np
import pandas as pd
from sklearn import linear_model


#and visualization setup
import matplotlib.pyplot as plt
%matplotlib inline  
plt.rcParams['figure.figsize'] = (10, 6)

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

In [2]:
urls_array=[
            "https://www.basketball-reference.com/leagues/NBA_1980_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_1983_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_1985_totals.html"
           ,"https://www.basketball-reference.com/leagues/NBA_1988_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_1990_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_1992_totals.html"
           ,"https://www.basketball-reference.com/leagues/NBA_1995_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_1997_totals.html"
           ,"https://www.basketball-reference.com/leagues/NBA_1999_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2001_totals.html"
          ,"https://www.basketball-reference.com/leagues/NBA_2003_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2005_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2008_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2010_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2012_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2015_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2017_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2019_totals.html"
            ,"https://www.basketball-reference.com/leagues/NBA_2021_totals.html"
           ]

urls_2_array=[
               "https://www.basketball-reference.com/international/fiba-world-cup/2010_totals.html"
                ,"https://www.basketball-reference.com/international/fiba-world-cup/2014_totals.html"
                ,"https://www.basketball-reference.com/international/fiba-world-cup/2019_totals.html"
                ,"https://www.basketball-reference.com/international/cba-china/2012_totals.html"
                ,"https://www.basketball-reference.com/international/cba-china/2014_totals.html"
                ,"https://www.basketball-reference.com/international/cba-china/2016_totals.html"
                ,"https://www.basketball-reference.com/international/cba-china/2018_totals.html"
                ,"https://www.basketball-reference.com/international/cba-china/2020_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2003_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2005_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2007_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2009_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2011_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2013_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2015_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2017_totals.html"
                ,"https://www.basketball-reference.com/international/eurocup/2019_totals.html"
    
]

players=list()
#age_s=list()
p3_s=list()
p3a_s=list()
p3p_s=list()
p2_s=list()
p2a_s=list()
p2p_s=list()
ft_s=list()
fta_s=list()
ftp_s=list()
orb_s=list()
drb_s=list()
ast_s=list()

In [3]:
for url in urls_array:
    html = requests.get(url)
    soup = BeautifulSoup(html.content, "html.parser")
    table = soup.find('table')
    table_rows = table.find_all('tr')
    for tr in table_rows:
        td = tr('td')
        row = [tr.text.strip() for tr in td if tr.text.strip()]
        if row:
            players.append(row[0])
            #age_s.append(row[2])
            p3_s.append(row[10])
            p3a_s.append(row[11])        
            p3p_s.append(row[12])
            p2_s.append(row[13])
            p2a_s.append(row[14])
            p2p_s.append(row[15])
            ft_s.append(row[17])
            fta_s.append(row[18])
            ftp_s.append(row[19])
            orb_s.append(row[20])
            drb_s.append(row[21])
            ast_s.append(row[23])


    for i in range(0,len(p2p_s)):
        if (str(p2p_s[i])[0]!="."):
            p2p_s[i]=999
            
    for i in range(0,len(p3p_s)):
        if (str(p3p_s[i])[0]!="."):
            p3p_s[i]=999

In [4]:
for url2 in urls_2_array:
    html2 = requests.get(url2)
    soup2 = BeautifulSoup(html2.content, "html.parser")
    table2 = soup2.find('table')
    table_rows2 = table2.find_all('tr')
    for tr in table_rows2:
        
        th2=tr('th')
        row2 = [tr.text.strip() for tr in th2 if tr.text.strip()]
        if row2:
            players.append(row2[0])
            
        td2 = tr('td')
        row = [tr.text.strip() for tr in td2 if tr.text.strip()]
        if row:
            p3_s.append(row[6])
            p3a_s.append(row[7])        
            p3p_s.append(row[8])
            p2_s.append(row[9])
            p2a_s.append(row[10])
            p2p_s.append(row[11])
            ft_s.append(row[13])
            fta_s.append(row[14])
            ftp_s.append(row[15])
            orb_s.append(row[16])
            drb_s.append(row[17])
            ast_s.append(row[19])

    players.remove('Player')

In [5]:
for i in range(0,len(p3p_s)):
    if (str(p3a_s[i])[0]=="."):
        p3a_s[i]=999
    if (str(p3a_s[i])=="1.000"):
         p3a_s[i]=999
        
for i in range(0,len(p3p_s)):
    if (str(ft_s[i])[0]=="."):
        ft_s[i]=999
    if (str(ft_s[i])=="1.000"):
         ft_s[i]=999

for i in range(0,len(p3p_s)):
    if (str(p2a_s[i])[0]=="."):
        p2a_s[i]=999
    if (str(p2a_s[i])=="1.000"):
         p2a_s[i]=999
            
for i in range(0,len(p3p_s)):
    if (str(fta_s[i])[0]=="."):
        fta_s[i]=999
    if (str(fta_s[i])=="1.000"):
         fta_s[i]=999
            
for i in range(0,len(p2p_s)):
    p3_s[i]=(int)(p3_s[i])
    orb_s[i]= (int)(orb_s[i])
    p3a_s[i]= (int)(p3a_s[i])
    p2a_s[i]= (int)(p2a_s[i])
    ft_s[i]= (int)(ft_s[i])
    fta_s[i]= (int)(fta_s[i])
    drb_s[i]= (int)(drb_s[i])
    ast_s[i]= (int)(ast_s[i])
    
    
for i in range(0,len(p2p_s)):
    if p3p_s[i]!=999:
        if (p3p_s[i][0]=="."):
            p3p_s[i]=(float)(p3p_s[i])
            p3p_s[i]= p3p_s[i]*100
            p3p_s[i]= round (p3p_s[i],2)
            p3p_s[i]=(int)(p3p_s[i])


  

In [6]:
success=list()
for i in range(0,len(p3p_s)):
    if(p3p_s[i]!=999):
        if((float)(p3p_s[i])>35):
            success.append(1)
        else:
            success.append(0)
    else: success.append(999)


In [7]:
df = pd.DataFrame({"Player Name":players,"Success":success,"3P":p3_s,"3PA":p3a_s,"3P%":p3p_s,"2P":p2_s,"2PA":p2a_s,"2P%":p2p_s,"FT":ft_s,"FTA":fta_s,"FT%":ftp_s,"ORB":orb_s,"DRB":drb_s,"AST":ast_s})
df.drop_duplicates(subset='Player Name', keep='first', inplace=True)

df = df[df["2P%"]!= 999]
df.shape
df = df[df["3P%"]!=999]
df.shape  

df = df[df["3P"]>3]
df.shape 

df=df.drop(['Player Name'], axis=1)
df=df.drop(['3P%'], axis=1)
df=df.drop(['2P%'], axis=1)
df=df.drop(['FT%'], axis=1)


df.describe()

Success           3P          3PA          2PA           FT  \
count  2720.000000  2720.000000  2720.000000  2720.000000  2720.000000   
mean      0.423162    24.401838    70.077574   169.364338    49.485662   
std       0.494151    29.786168    81.601289   243.031628    71.418696   
min       0.000000     4.000000     4.000000     0.000000     0.000000   
25%       0.000000     7.000000    21.000000    26.000000     9.000000   
50%       0.000000    13.000000    38.000000    62.000000    22.000000   
75%       1.000000    28.000000    80.000000   202.250000    56.250000   
max       1.000000   226.000000   572.000000  1594.000000   630.000000   

               FTA          ORB          DRB          AST  
count  2720.000000  2720.000000  2720.000000  2720.000000  
mean     66.392279    26.115074    71.320221    67.862868  
std      98.484120    37.755115    88.122804   106.126393  
min       0.000000     0.000000     0.000000     0.000000  
25%      12.000000     4.000000    15.000000    11.000000  
50%      30.000000    12.000000    34.000000    26.000000  
75%      76.000000    31.000000    92.000000    74.000000  
max     999.000000   340.000000   711.000000   925.000000

In [8]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [9]:
X = df.iloc[:,1:].values
y = df["Success"].values

XTrain, XTest, yTrain, yTest = train_test_split(X, y, random_state=1, test_size=0.35)

In [10]:
gnb = GaussianNB()


# Train classifier
gnb.fit(XTrain,yTrain)

y_pred = gnb.predict(XTest)
y_pred_train = gnb.predict(XTrain)

# Print results
print('Accuracy on Train data= ', metrics.accuracy_score(y_true = yTrain, y_pred = y_pred_train))
print('Accuracy on test data= ', metrics.accuracy_score(y_true = yTest, y_pred = y_pred))

Accuracy on Train data=  0.5395927601809954
Accuracy on test data=  0.5


In [11]:
gnb.class_prior_

array([0.56674208, 0.43325792])

In [12]:
gnb.theta_

array([[ 22.88722555,  73.6007984 , 102.14570858, 213.85429142,
         61.83133733,  83.71457086,  32.4251497 ,  84.20259481,
         83.97804391],
       [ 27.86422977,  68.73237598,  52.42167102, 108.89686684,
         34.01174935,  44.94386423,  16.77154047,  51.35770235,
         46.88903394]])

In [13]:
gnb.sigma_

array([[  753.97237006,  6518.88460846, 18389.25427631, 77839.88102282,
         6906.89875681, 13277.17008541,  1895.99695064,  8789.30931294,
        13916.17921685],
       [ 1179.51426172,  7761.10467579,  6082.14731703, 26264.44503533,
         2352.280599  ,  4806.26192003,   564.80295583,  4900.87732916,
         6117.86111288]])